sudo: required
services:
  - docker

before_install:
  - docker build -t smozam/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true smozam/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "travis-e3912d38190828d169c0973be74eed6a14d73f9a-1566413272.zip"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-229081260233"
  bucket_path: "travis-e3912d38190828d169c0973be74eed6a14d73f9a-1566413272.zip"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
