sudo: required
services:
  - docker

before_install:
  - docker build -t smozam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smozam/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-229081260233"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
